String.toLocaleString({
    
	"it": {
		"%game-intro"           : "Race the <strong>Ferraris!</strong>",
		"%restart-button"       : "Race Again",
		"%keep-playing-button"  : "Keep going",
		"%retry-button"         : "Retry",
		"%game-won"             : "You won the Grand Prix!",
		"%game-over"            : "Game over, back to the pits!",
		"%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a rebranded version of the original 2048 made by Gabriele Cirulli.</a>.",
		"%credits"              : "Originally created by Gabriele Cirulli, modified by Ethan Hood.",
		"%tweet1"               : "I scored \"",
		"%tweet2"               : "\" at 2048-FERRARI #2048game",
		"%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
		'%2'                    : '125 S',
    '%4'                    : '250 GTO',
    '%8'                    : 'Testarossa',
    '%16'                   : 'F40',
    '%32'                   : 'Enzo',
    '%64'                   : '599 GTB',
    '%128'                  : 'F12 Berlinetta',
    '%256'                  : 'F60 America',
    '%512'                  : '458 Speciale',
    '%1024'                 : 'California T',
    '%2048'                 : '488 Spider',
		'%p0'                   : '125 S',
    '%p4'                   : '250 GTO',
    '%p8'                   : 'Testarossa',
    '%p16'                  : 'F40',
    '%p32'                  : 'Enzo',
    '%p64'                  : '599 GTB',
    '%p128'                 : 'F12 Berlinetta',
    '%p256'                 : 'F60 America',
    '%p512'                 : '458 Speciale',
    '%p1024'                : 'California T',
    '%p2048'                : '488 Spider',
	},
	
	"en": {
		"%game-intro"           : "Race the <strong>Ferraris!</strong>",
		"%restart-button"       : "Race Again",
		"%keep-playing-button"  : "Keep going",
		"%retry-button"         : "Retry",
		"%game-won"             : "You won the Grand Prix!",
		"%game-over"            : "Game over, back to the pits!",
		"%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"https://ethanhood.github.io/2048f/\">ethan.hood.github.io./2048f</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%credits"              : "Originally created by Gabriele Cirulli, modified by Ethan Hood.",
		"%tweet1"               : "I scored \"",
		"%tweet2"               : "\" at 2048-FERRARI #2048game",
		"%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
		'%2'                    : '125 S',
    '%4'                    : '250 GTO',
    '%8'                    : 'Testarossa',
    '%16'                   : 'F40',
    '%32'                   : 'Enzo',
    '%64'                   : '599 GTB',
    '%128'                  : 'F12 Berlinetta',
    '%256'                  : 'F60 America',
    '%512'                  : '458 Speciale',
    '%1024'                 : 'California T',
    '%2048'                 : '488 Spider',
		'%p0'                   : '125 S',
    '%p4'                   : '250 GTO',
    '%p8'                   : 'Testarossa',
    '%p16'                  : 'F40',
    '%p32'                  : 'Enzo',
    '%p64'                  : '599 GTB',
    '%p128'                 : 'F12 Berlinetta',
    '%p256'                 : 'F60 America',
    '%p512'                 : '458 Speciale',
    '%p1024'                : 'California T',
    '%p2048'                : '488 Spider',
	}

});
